on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - uses: actions/checkout@v1
      - run: pip install -e .
      - run: pip install pytest
      - name: Cache Drafter
        uses: actions/cache@v1
        id: cache-drafter
        with:
          path: lib
          key: ${{ runner.os }}-drafter-4.1.0
      - name: Install Drafter
        if: steps.cache-drafter.outputs.cache-hit != 'true'
        run: |
          mkdir lib
          wget https://github.com/apiaryio/drafter/releases/download/v4.1.0/drafter-4.1.0.tar.gz
          tar xvf drafter-4.1.0.tar.gz
          mkdir drafter-4.1.0/build
          cd drafter-4.1.0/build
          cmake ..
          make -j4 drafter-lib
          cp ./src/libdrafter.so ../../lib
      - run: pytest

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - run: pip install -e .
      - run: pip install flake8
      - run: flake8 draughtsman tests
